spring:
  application:
    name: chat-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8889}"

#server:
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: kurento
#    key-store-type: JKS
#    key-alias: kurento-selfsigned